apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-sale-app
  labels:
    app: flash-sale
spec:
  replicas: 3                         # 3 pods for high availability
  selector:
    matchLabels:
      app: flash-sale
  template:
    metadata:
      labels:
        app: flash-sale
    spec:
      containers:
        - name: flash-sale
          image: your-dockerhub-username/flash-sale-system:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/flash-sale/product/1
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5